name: Deploy to central-config
description: Deploy to central-config
inputs:
  APP:
    description: For example `health-hub-web`
    required: true
  APP_PATH:
    description: For example `frontend/health-hub-web`
    required: true
  COUNTRY:
    description: For example `ae`
    required: true
  STAGE:
    description: For example `acc`
    required: true
  TAG:
    description: For example `v1.2.3`
    required: true
runs:
  using: 'composite'
  steps:
    - name: Deploy ${{ inputs.APP }}@${{ inputs.TAG }} to ${{ inputs.COUNTRY }}-${{ inputs.STAGE }}
      shell: bash
      working-directory: ./.carepay-actions
      run: ./.github/actions/deploy/central-config-updater.sh
      env:
        APP: ${{ inputs.APP }}
        APP_PATH: ${{ inputs.APP_PATH }}
        COUNTRY: ${{ inputs.COUNTRY }}
        STAGE: ${{ inputs.STAGE }}
        TAG: ${{ inputs.TAG }}
